export AUTH0_DOMAIN="drdilyor.us.auth0.com"
export API_AUDIENCE="fsnd-capstone"
export DATABASE="postgresql://postgres:postgres@localhost:5432/fsnd_capstone"
alias m="python manage.py"
alias d="m db"
